# -*- coding: utf-8 -*-
"""rule_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJJm5CCzCHBWpV1MxQ5QZn13_tV7SHCE
"""

# Commented out IPython magic to ensure Python compatibility.
# # Create test_logs.py in current Colab session
# %%writefile test_logs.py
# from datetime import datetime, timedelta
# 
# def sample_logs():
#     return [
#         {'user_id': 'U01', 'role': 'user', 'action': 'view',
#          'timestamp': datetime(2025, 10, 18, 23, 30),
#          'event': 'login', 'actions_per_min': 10},
#         {'user_id': 'U02', 'role': 'user', 'action': 'login',
#          'timestamp': datetime.now(), 'event': 'failed_login', 'actions_per_min': 2},
#         {'user_id': 'U02', 'role': 'user', 'action': 'login',
#          'timestamp': datetime.now(), 'event': 'failed_login', 'actions_per_min': 2},
#         {'user_id': 'U03', 'role': 'auditor', 'action': 'delete',
#          'timestamp': datetime.now(), 'event': 'action', 'actions_per_min': 5},
#         {'user_id': 'U04', 'role': 'user', 'action': 'create',
#          'timestamp': datetime.now(), 'event': 'action', 'actions_per_min': 80},
#         {'user_id': 'U05', 'role': 'admin', 'action': 'update',
#          'timestamp': datetime.now(), 'event': 'verify', 'actions_per_min': 10}
#     ]
#