# -*- coding: utf-8 -*-
"""test_logs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6v0KBsJo7nlZSj5BuExESrLf7IaeDkg
"""

from datetime import datetime, timedelta

def sample_logs():
    """Generate sample logs that trigger all 5 rules."""
    return [
        # 1️⃣ Access outside office hours
        {'user_id': 'U01', 'role': 'user', 'action': 'view',
         'timestamp': datetime(2025, 10, 18, 23, 30),
         'event': 'login', 'actions_per_min': 10},

        # 2️⃣ Five failed logins within 5 minutes
        {'user_id': 'U02', 'role': 'user', 'action': 'login',
         'timestamp': datetime.now(), 'event': 'failed_login', 'actions_per_min': 2},
        {'user_id': 'U02', 'role': 'user', 'action': 'login',
         'timestamp': datetime.now() + timedelta(seconds=30), 'event': 'failed_login', 'actions_per_min': 2},
        {'user_id': 'U02', 'role': 'user', 'action': 'login',
         'timestamp': datetime.now() + timedelta(seconds=60), 'event': 'failed_login', 'actions_per_min': 2},
        {'user_id': 'U02', 'role': 'user', 'action': 'login',
         'timestamp': datetime.now() + timedelta(seconds=90), 'event': 'failed_login', 'actions_per_min': 2},
        {'user_id': 'U02', 'role': 'user', 'action': 'login',
         'timestamp': datetime.now() + timedelta(seconds=120), 'event': 'failed_login', 'actions_per_min': 2},

        # 3️⃣ Role violation
        {'user_id': 'U03', 'role': 'auditor', 'action': 'delete',
         'timestamp': datetime.now(), 'event': 'action', 'actions_per_min': 5},

        # 4️⃣ Rate spike detection
        {'user_id': 'U04', 'role': 'user', 'action': 'create',
         'timestamp': datetime.now(), 'event': 'action', 'actions_per_min': 80},

        # 5️⃣ Integrity break
        {'user_id': 'U05', 'role': 'admin', 'action': 'update',
         'timestamp': datetime.now(), 'event': 'verify', 'actions_per_min': 10}
    ]